### ISSUE TITLE
Fission.io website not loading properly

### ISSUE THREAD

**Issue by jdziat** [fission/fission.io#101]
**Fission/Kubernetes version**

<pre>
$ fission --version
$ kubectl version
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**

**Describe the bug**

**To Reproduce**
Visit the website

**Expected result**

Loads and displays properly

**Actual result**
Fails to load the file: https://fission.io/scss/main.min.3a11f6677f03a755cbda7bb8bd7a2d08ffe0ceba6bada3a2a1423500743622ce.css

**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>

**Additional context**

**Comment by sanketsudake** [comment]
@jdziat could you try doing hard refresh ?

**Comment by jdziat** [comment]
Seems to be working now. Thanks
