### ISSUE TITLE
[docbug]Typo in section Running container as functions

### ISSUE THREAD

**Issue by meganeshkadam** [fission/fission.io#129]
I believe, [here is a small typo]( https://fission.io/docs/usage/function/container-functions/ ):
~~~
fission function run-container provides required options to run an **exiting** container image as a Fission function.
~~~

It should be `existing`  instead of `exiting?`

**Comment by meganeshkadam** [comment]
I can modify this and send a PR, just need confirmation. I have a local Hugo setup running already.

**Comment by sanketsudake** [comment]
@meganeshkadam  Thanks for identifying this 👍 . Feel free to raise PR.

**Comment by meganeshkadam** [comment]
Not sure, someone corrected it before me! :D

**Comment by sanketsudake** [comment]
No it still exists. Raised PR https://github.com/fission/fission.io/pull/132
