### ISSUE TITLE
Metrics with Prometheus

### ISSUE THREAD

**Issue by LinYKen** [fission/fission.io#149]
How can I expose the grafana port so that I can visit the webpage from external?

**Comment by sanketsudake** [comment]
Hi @LinYKen ,

You simply need to port forward to your grafana UI and access dashboard.

We have also added metrics reference recently to understand what all metrics Fission provides.

https://fission.io/docs/reference/metrics-reference/

I hope this answers this question, feel free to reopen if any further queries. We are also enhancing our existing metrics references.
