### ISSUE TITLE
Blog seems to be down

### ISSUE THREAD

**Issue by bumblefudge** [fission/fission.io#230]
https://fission.codes/blog/wallet-stack/
![image](https://github.com/fission/fission.io/assets/37127325/f372b21b-d22b-4410-a553-2a96c4e12af5)

**Comment by techmaharaj** [comment]
Hi @bumblefudge, the URL seems to be incorrect. The blog can be accessed at https://fission.io/blog/

**Comment by bumblefudge** [comment]
Yup! Old URL came from Google, which implies maybe a redirect rule is worth setting up.

But I can't find Ryan's wallet stack article on the new blog? Did it get missed in the migration?

**Comment by depatchedmode** [comment]
> Hi @bumblefudge, the URL seems to be incorrect. The blog can be accessed at https://fission.io/blog/

That's actually a different company named Fission. The URL @bumblefudge posted above should be correct. May have accidentally been unpublished while we were migrating to the new version of the website because a quick scan doesn't reveal it in the blog index either.

On it!

**Comment by depatchedmode** [comment]
And here is where I realize we are actually in the other company's repo @bumblefudge. Haha.

We will see ourselves to the door. Carry on name twins!
