### ISSUE TITLE
Website not available

### ISSUE THREAD

**Issue by simcod** [fission/fission.io#231]
**Describe the bug**

Currently, I can not access the [fission.io](https://fission.io/) website. There may be something wrong with the certificates.

**To Reproduce**

Visit the [fission.io](https://fission.io/) website.

**Expected result**

It would be nice to navigate the site again and read the documentation, etc.

**Actual result**
Currently, I get an connection error within firefox and chrome.

**Comment by bosmak** [comment]
The domain expired.

When visiting it using http, it redirects me to a GoDaddy parked domain page.

http://fission.io

**Comment by simcod** [comment]
Thanks, it is working again!
