### ISSUE TITLE
Add PWA support for the application with offline support 

### ISSUE THREAD

**Issue by Aniket762** [fission/fission.io#53]
A progressive web application is a type of application software delivered through the web, built using common web technologies including HTML, CSS, and JavaScript. It is intended to work on any platform that uses a standards-compliant browser, including both desktop and mobile devices. Progressive Web Apps (PWAs) allow developers to deliver an app-like experience to the user.

I would like to work on the issue, in case you don't want PWA support feel free to close the issue! Looking forward to working contribute to one of the best Org out there ⚡️

**Comment by sanketsudake** [comment]
Hi @Aniket762 

Could you have any thoughts on what would be efforts to this ?
Also for the current website we use [hugo framework](https://gohugo.io/) and [docsy base theme](https://www.docsy.dev/).

**Comment by Aniket762** [comment]
Hey, @sanketsudake thanks for replying means a lot. From the documentation I got it's built on Hugo, as I have never implemented PWA with Hugo, I googled it and it was pretty smooth. I would like to give it a shot. I hope that's what you asked for! 

Can you please assign this to me?

**Comment by sanketsudake** [comment]
Thanks for your interest. 👍  Assigned it.

**Comment by Aniket762** [comment]
Hey, @sanketsudake I have sent the PR do check it out. I have also deployed my version on Netlify and it is working 

Here is the link: https://naughty-lumiere-b1b148.netlify.app/

Hopefully, it works on the master prod
